use_frameworks!

platform :ios, '9.0'

target 'XHFontPicker_Example' do
  pod 'XHFontPicker', :path => '../'

  target 'XHFontPicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
